### PR TITLE
Add support for macos

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by angerman** [comment]
The only issue I have with this, is that it requires the existence of `gtar` and `gdate`, which means it won't work for me :-/

**Comment by newhoggy** [comment]
It doesn't require the existence of `gtar` and `gdate`.  If there is a `tar` or `date` in the `PATH` that isn't the default version of those, then it will prefer that.

**Comment by angerman** [comment]
```
angerman@Moritzs-MacBook-Air> which tar
/usr/bin/tar
```

```
angerman@Moritzs-MacBook-Air> which gtar
gtar not found
```

but ultimately I'll figure out a way around.

**Comment by michaelpj** [comment]
I'm okay with this if it's the generally approved way of doing this (surely we can't be the first people with this problem), but it needs a comment.

**Comment by newhoggy** [comment]
I moved the BSD date/tar handling to a separate script and added a comment.

**Review by michaelpj — APPROVED** [review]

**Pull request merged**
