### PR TITLE
Update `cardano-base` packages

### PR DESCRIPTION
**Pull request by Lucsanszky**

### CODE REVIEW

**Comment by Lucsanszky** [comment]
@lehins, should we also release some newer versions of other packages? It seems like `cardano-mempool` was never released and `cardano-crypto-praos` has some funkiness going on with its versions (on CHaP, the current version is `2.1.2.0` but the current version according to the `.cabal` file is `2.1.1.2`). `cardano-crypto-class` also has a newer version but the `CHANGELOG` states that we shouldn't release that yet so I won't.

**Comment by lehins** [comment]
> should we also release some newer versions of other packages?

@Lucsanszky No. As you did notice in the changlog, those packages are not ready be released yet.

https://github.com/IntersectMBO/cardano-base/blob/f11ddc7f87038c16d5a6d7611fb5dda51be9533d/cardano-crypto-class/CHANGELOG.md?plain=1#L5-L6

**Review by lehins — CHANGES_REQUESTED** [review]
This looks good, but we need to fix all of the versions of cardano-ledger-shelley from 1.0.0.0 to 1.9.0.0, not just 1.2.0.0 and 1.9.0.0 since we know that they are too incompatible with `cardano-slotting-0.2`. 
The fact that CI didn't pick up on them doesn't mean those versions would not break if they got picked up by cabal solver. Since we know about this incompatibility, we should do the due diligence and prevent such build plan to ever exist.

So, yeah, just and adding a whole bunch more revisions like that and we'll be good with the PR :slightly_smiling_face:

**Review by lehins — APPROVED** [review]
Perfect! Thank you.

**Pull request merged**
